# HTML

# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages: 
 - stage: Build
   displayName: Create Blob Storage
   jobs:
   - job: Build
     displayName: "Executing Terraform" 
     pool:
          vmImage: 'windows-latest'
     variables:
     - group: TerraformEnvVars
     steps:
       - task: TerraformTaskV1@0
         displayName: "Terraform Install"
         inputs:
           provider: 'azurerm'
           command: 'init'
           backendAzureRmResourceGroupName: 'tf_rgblobstorage'
           backendAzureRmStorageAccountName: 'tfstatechetan'
           backendAzureRmContainerName: 'tfstatechetan'
           backendAzureRmKey: 'terraform.tfstate'
       - task: TerraformTaskV1@0
         displayName: "Terraform Validate"
         inputs:
          provider: 'azurerm'
          command: 'validate'
       - task: TerraformTaskV1@0
         displayName: "Terraform Applying Step"
         inputs:
           provider: 'azurerm'
           command: 'apply'
           environmentServiceNameAzureRM: 'AuthServiceConn'
 - stage:
   dependsOn: Build
   displayName: "Running Copy"
   jobs:
     - job: Copying
       steps:
         - task: AzureFileCopy@2
           displayName: "Copying file"
           inputs:
              azureSubscription: 'AuthServiceConn'
              SourcePath: "$(System.DefaultWorkingDirectory)/personalwebsite1"
              Destination: 'AzureBlob'
              ContainerName: '$web'
            
