# HTML

# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages: 
 - stage: Build
   displayName: Create Blob Storage
   jobs:
   - job: Build
     displayName: "Executing Terraform" 
     pool:
          vmImage: 'windows-latest'
     variables:
     - group: TerraformEnvVars
     steps:
       - script: | 
            set -e
            
            terraform init -input=false
            terraform apply -input=false -auto-approve
         name: RunningTerraformScript
         env:
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
 - stage:
   dependsOn: Build
   displayName: "Running Copy"
   jobs:
     - job: Copying
       steps:
         - task: AzureFileCopy@2
           displayName: "Copying file"
           env:
             ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
           inputs:
              azureSubscription: $(ARM_SUBSCRIPTION_ID)
              SourcePath: "$(System.DefaultWorkingDirectory)/personalwebsite1"
              Destination: 'AzureBlob'
              ContainerName: '$web'
            
