# HTML

# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
 
- task: AzureFileCopy@4
  inputs:
    azureSubscription: 'Free Trial(35666c79-7f9c-4633-96b2-b16f9ca526fe)'
    Destination: 'AzureBlob'
    storage: 'tfstoragecheetah1989'
    ContainerName: 'static-content'
