# HTML

# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages: 
 - stage: Build
   displayName: Create Blob Storage
   jobs:
   - job: Build
     displayName: "Executing Terraform"
     pool:
       vmImage: "windows-latest"
     variables:
     - group: TerraformEnvVars
     steps:
     - pwsh: |
        terraform init -input=false
        terraform apply -input=false -auto-approve
       name: 'RunTerraForm'
       displayName: "Run TerraForm Code"
       env:
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
         ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
         ARM_TENANT_ID: $(ARM_TENANT_ID)
         ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
 - stage:
   dependsOn: Build
   displayName: "Running Copy"
   jobs:
     - job: Copying
       pool:
         vmImage: 'windows-latest'
       steps:
         - task: AzureFileCopy@4
           inputs:
             SourcePath: '$(System.DefaultWorkingDirectory)/personalwebsite1/code/'
             azureSubscription: 'AuthServiceConn'
             Destination: 'AzureBlob'
             storage: 'tfstatechetan'
             ContainerName: '$web'

         
            
